app:
  name: app
  version: 0.1

logging:
  level: info

database:
  quantdb: 'mysql+pymysql://quant:quant@localhost:3306/quant'

gtja:
  access_key_id: '********************************'
  access_key_secret: '********************************'

htzq:
  user: '********'
  password: '********'

dzqh:
  app_key: '********************************'
  app_secret: '********************************'